import{a as u,S as p,i as d}from"./assets/vendor-3fcf03a1.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const f="42508369-6cc99fb978405cb8598a23b23",m="https://pixabay.com/api/",h="photo",y="horizontal",g=!0;async function E(n){const t=encodeURIComponent(n),s=`${m}?key=${f}&q=${t}&image_type=${h}&orientation=${y}&safesearch=${g}`;try{return(await u.get(s)).data}catch(r){throw console.error("Error fetching images:",r),new Error("Error while fetching images from Pixabay")}}function L(n,t){t.innerHTML="",t.innerHTML=n.map(r=>` <div class="card">
         <a href="${r.webformatURL}"><img class="card-image" src="${r.webformatURL}" alt="${r.tags}" />
         <div class="card-info">
           <p>Likes: <span>${r.likes}</span></p>
           <p>Views: <span>${r.views}</span></p>
           <p>Comments: <span>${r.comments}</span></p>
           <p>Downloads:<span>${r.downloads}</span></p>
         </div></a>
       </div> `).join(""),new p(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}function a(n){d.error({title:"Error",message:n,position:"topRight"})}const b=document.querySelector(".form"),c=document.querySelector(".search-input"),$=document.querySelector(".gallery"),l=document.querySelector(".loader");b.addEventListener("submit",function(n){n.preventDefault();const t=c.value.trim();if(t===""){a("Please fill imput");return}l.classList.remove("is-hidden"),E(t).then(s=>{if(s.hits.length===0){a("Sorry, there are no images matching your search query. Please try again!");return}L(s.hits,$),c.value=""}).catch(s=>{console.error("Error during search:",s),a("Error")}).finally(()=>{l.classList.add("is-hidden")})});
//# sourceMappingURL=commonHelpers.js.map
